## EDA

In [86]:
import pandas as pd
import numpy as np

In [87]:
df = pd.read_csv("sample_data/ta_restaurants.csv")
df.head()

  rating  reviews_count                  cuisine_type     price  is_sponsored
0    5,0              3  Средиземноморская, Греческая  $$ - $$$          True
1    4,1             97      Бары и клубы, Стейк-хаус  $$ - $$$          True
2    4,8           3316       Французская, Стейк-хаус      $$$$         False
3    4,3            518           Китайская, Японская         $         False
4    4,7           3995            Итальянская, Пицца  $$ - $$$         False

In [88]:
df.shape

(10499, 5)

In [89]:
df['rating'] = df['rating'].str.replace(',', '.').astype('float')

In [90]:
df.isna().sum()

rating           1818
reviews_count       0
cuisine_type      293
price            4234
is_sponsored        0
dtype: int64

In [91]:
df = df.dropna(subset=['rating', 'price', 'cuisine_type'])

In [92]:
price_levels = ['$', '$$', '$$$', '$$$$', '$$$$$']

for price_level in price_levels:
  df[price_level] = df['price'].fillna('').apply(
      lambda x: int(price_level in x.replace(' ', '').split('-'))
  )

In [93]:
df

,rating,reviews_count,cuisine_type,price,is_sponsored,$,$$,$$$,$$$$,$$$$$
0,5.0,3,"Средиземноморская, Греческая",$$ - $$$,True,0,1,1,0,0
1,4.1,97,"Бары и клубы, Стейк-хаус",$$ - $$$,True,0,1,1,0,0
2,4.8,3316,"Французская, Стейк-хаус",$$$$,False,0,0,0,1,0
3,4.3,518,"Китайская, Японская",$,False,1,0,0,0,0
4,4.7,3995,"Итальянская, Пицца",$$ - $$$,False,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
10463,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0
10464,4.5,130,"Бары и клубы, Ирландская",$,True,1,0,0,0,0
10465,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0
10482,4.5,27,"Японская, Азиатская",$$ - $$$,True,0,1,1,0,0
10498,4.4,30,"Китайская, Азиатская",$$ - $$$,True,0,1,1,0,0

In [94]:
df = df[~df['cuisine_type'].fillna('').str.contains(
    r'Откроется|Закроется|Открыто|Сейчас|Сегодня|Меню', regex=True)]

In [99]:
cuisine_dummies = df['cuisine_type'].str.get_dummies(sep=', ')
cuisine_dummies.columns = cuisine_dummies.columns.str.replace(' ', '_').str.replace('-', '_')
cuisine_dummies.columns.tolist()

['Австралийская',
 'Австрийская',
 'Азиатская',
 'Американская',
 'Аргентинская',
 'Армянская',
 'Афганская',
 'Африканская',
 'Бангладешская',
 'Бар',
 'Барбекю',
 'Бары_и_клубы',
 'Бары_с_рестораном',
 'Баскская',
 'Бельгийская',
 'Ближневосточная',
 'Бразильская',
 'Британская',
 'Венесуэльская',
 'Винный_бар',
 'Восточноевропейская',
 'Вьетнамская',
 'Гавайская',
 'Гастроном',
 'Гастропаб',
 'Греческая',
 'Гриль',
 'Грузинская',
 'Десерты',
 'Европейская',
 'Закусочная',
 'Здоровая',
 'Израильская',
 'Индийская',
 'Ирландская',
 'Испанская',
 'Итальянская',
 'Каджунская_и_креольская',
 'Кайсэки',
 'Канадская',
 'Кантонская',
 'Карибская',
 'Кафе',
 'Китайская',
 'Корейская',
 'Кубинская',
 'Латиноамериканская',
 'Ливанская',
 'Малазийская',
 'Марокканская',
 'Международная',
 'Мексиканская',
 'Морепродукты',
 'Немецкая',
 'Нонья',
 'Паб',
 'Паб_с_пивоварней',
 'Пакистанская',
 'Персидская',
 'Перуанская',
 'Пицца',
 'Польская',
 'Португальская',
 'Римская',
 'Русская',
 'Северно_итальянская',
 'Сицилийская',
 'Современная',
 'Средиземноморская',
 'Стейк_хаус',
 'Супы',
 'Суши',
 'Сычуаньская',
 'Тайваньская',
 'Тайская',
 'Тибетская',
 'Тосканская',
 'Турецкая',
 'Украинская',
 'Уличная_еда',
 'Фастфуд',
 'Филиппинская',
 'Французская',
 'Фьюжн',
 'Хорватская',
 'Центральноазиатская',
 'Центральноамериканская',
 'Чешская',
 'Шанхайская',
 'Шведская',
 'Швейцарская',
 'Шриланкийская',
 'Эфиопская',
 'Юговосточная',
 'Южноамериканская',
 'Юнаньская',
 'Ямайская',
 'Японская',
 'Японская_кухня_фьюжн']

In [100]:
df = pd.concat([df, cuisine_dummies], axis=1)

In [101]:
df

,rating,reviews_count,cuisine_type,price,is_sponsored,$,$$,$$$,$$$$,$$$$$,...,Шведская,Швейцарская,Шриланкийская,Эфиопская,Юговосточная,Южноамериканская,Юнаньская,Ямайская,Японская,Японская_кухня_фьюжн
0,5.0,3,"Средиземноморская, Греческая",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4.1,97,"Бары и клубы, Стейк-хаус",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.8,3316,"Французская, Стейк-хаус",$$$$,False,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,4.3,518,"Китайская, Японская",$,False,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,4.7,3995,"Итальянская, Пицца",$$ - $$$,False,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10463,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10464,4.5,130,"Бары и клубы, Ирландская",$,True,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10465,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10482,4.5,27,"Японская, Азиатская",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,1,0
10498,4.4,30,"Китайская, Азиатская",$$ - $$$,True,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0