## EDA

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("sample_data/ta_restaurants.csv")
df.head()

  rating  reviews_count                  cuisine_type     price  is_sponsored
0    5,0              3  Средиземноморская, Греческая  $$ - $$$          True
1    4,1             97      Бары и клубы, Стейк-хаус  $$ - $$$          True
2    4,8           3316       Французская, Стейк-хаус      $$$$         False
3    4,3            518           Китайская, Японская         $         False
4    4,7           3995            Итальянская, Пицца  $$ - $$$         False

In [19]:
df.shape

(10499, 5)

In [20]:
df['rating'] = df['rating'].str.replace(',', '.').astype('float')

In [21]:
df.isna().sum()

rating           1818
reviews_count       0
cuisine_type      293
price            4234
is_sponsored        0
dtype: int64

In [22]:
df = df.dropna(subset=["rating"])

In [23]:
price_levels = ['$', '$$', '$$$', '$$$$', '$$$$$']

for price_level in price_levels:
  df[price_level] = df['price'].fillna('').apply(
      lambda x: int(price_level in x.replace(' ', '').split('-'))
  )

In [24]:
df

,rating,reviews_count,cuisine_type,price,is_sponsored,$,$$,$$$,$$$$,$$$$$
0,5.0,3,"Средиземноморская, Греческая",$$ - $$$,True,0,1,1,0,0
1,4.1,97,"Бары и клубы, Стейк-хаус",$$ - $$$,True,0,1,1,0,0
2,4.8,3316,"Французская, Стейк-хаус",$$$$,False,0,0,0,1,0
3,4.3,518,"Китайская, Японская",$,False,1,0,0,0,0
4,4.7,3995,"Итальянская, Пицца",$$ - $$$,False,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
10463,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0
10464,4.5,130,"Бары и клубы, Ирландская",$,True,1,0,0,0,0
10465,4.6,56,"Итальянская, Пицца",$$ - $$$,True,0,1,1,0,0
10482,4.5,27,"Японская, Азиатская",$$ - $$$,True,0,1,1,0,0
10498,4.4,30,"Китайская, Азиатская",$$ - $$$,True,0,1,1,0,0

In [25]:
cuisine_dummies = df['cuisine_type'].str.get_dummies(sep=', ')
cuisine_dummies.columns.tolist()

['Австралийская',
 'Австрийская',
 'Азиатская',
 'Албанская',
 'Алжирская',
 'Американская',
 'Арабская',
 'Аргентинская',
 'Армянская',
 'Афганская',
 'Африканская',
 'Бангладешская',
 'Бар',
 'Барбекю',
 'Бары и клубы',
 'Бары с рестораном',
 'Баскская',
 'Бельгийская',
 'Ближневосточная',
 'Бразильская',
 'Британская',
 'Венесуэльская',
 'Винный бар',
 'Восточноевропейская',
 'Вьетнамская',
 'Гавайская',
 'Гастроном',
 'Гастропаб',
 'Греческая',
 'Гриль',
 'Грузинская',
 'Датская',
 'Десерты',
 'Европейская',
 'Закроется через 14\xa0мин.',
 'Закроется через 2\xa0мин.',
 'Закроется через 40\xa0мин.',
 'Закроется через 41\xa0мин.',
 'Закроется через 42\xa0мин.',
 'Закроется через 43\xa0мин.',
 'Закроется через 44\xa0мин.',
 'Закусочная',
 'Здоровая',
 'Израильская',
 'Индийская',
 'Ирландская',
 'Испанская',
 'Итальянская',
 'Каджунская и креольская',
 'Кайсэки',
 'Камбоджийская',
 'Канадская',
 'Кантонская',
 'Карибская',
 'Кафе',
 'Китайская',
 'Колумбийская',
 'Корейская',
 'Кубинская',
 'Латиноамериканская',
 'Ливанская',
 'Малазийская',
 'Марокканская',
 'Международная',
 'Мексиканская',
 'Меню',
 'Морепродукты',
 'Немецкая',
 'Непальская',
 'Нонья',
 'Откроется через 11\xa0мин.',
 'Откроется через 12\xa0мин.',
 'Откроется через 13\xa0мин.',
 'Откроется через 14\xa0мин.',
 'Откроется через 15\xa0мин.',
 'Откроется через 16\xa0мин.',
 'Откроется через 17\xa0мин.',
 'Откроется через 1\xa0мин.',
 'Откроется через 20\xa0мин.',
 'Откроется через 24\xa0мин.',
 'Откроется через 25\xa0мин.',
 'Откроется через 26\xa0мин.',
 'Откроется через 28\xa0мин.',
 'Откроется через 2\xa0мин.',
 'Откроется через 31\xa0мин.',
 'Откроется через 32\xa0мин.',
 'Откроется через 34\xa0мин.',
 'Откроется через 35\xa0мин.',
 'Откроется через 3\xa0мин.',
 'Откроется через 40\xa0мин.',
 'Откроется через 41\xa0мин.',
 'Откроется через 42\xa0мин.',
 'Откроется через 43\xa0мин.',
 'Откроется через 44\xa0мин.',
 'Откроется через 45\xa0мин.',
 'Откроется через 46\xa0мин.',
 'Откроется через 47\xa0мин.',
 'Откроется через 48\xa0мин.',
 'Откроется через 4\xa0мин.',
 'Откроется через 50\xa0мин.',
 'Откроется через 52\xa0мин.',
 'Откроется через 53\xa0мин.',
 'Откроется через 54\xa0мин.',
 'Откроется через 56\xa0мин.',
 'Откроется через 57\xa0мин.',
 'Откроется через 59\xa0мин.',
 'Откроется через 6\xa0мин.',
 'Открыто сейчас',
 'Паб',
 'Паб с пивоварней',
 'Пакистанская',
 'Персидская',
 'Перуанская',
 'Пицца',
 'Польская',
 'Португальская',
 'Пуэрториканская',
 'Римская',
 'Румынская',
 'Русская',
 'Северно-итальянская',
 'Сегодня выходной',
 'Сейчас закрыто',
 'Сингапурская',
 'Сицилийская',
 'Современная',
 'Средиземноморская',
 'Стейк-хаус',
 'Супы',
 'Суши',
 'Сычуаньская',
 'Тайваньская',
 'Тайская',
 'Тибетская',
 'Тосканская',
 'Турецкая',
 'Узбекская',
 'Украинская',
 'Уличная еда',
 'Фастфуд',
 'Филиппинская',
 'Французская',
 'Фьюжн',
 'Хорватская',
 'Центральноазиатская',
 'Центральноамериканская',
 'Чешская',
 'Чилийская',
 'Шанхайская',
 'Шведская',
 'Швейцарская',
 'Шриланкийская',
 'Эфиопская',
 'Юговосточная',
 'Южно-итальянская',
 'Южноамериканская',
 'Юнаньская',
 'Ямайская',
 'Японская',
 'Японская кухня-фьюжн']

In [26]:
cuisine_dummies = cuisine_dummies.filter(regex='^(?!Откроется|Закроется)')
cuisine_dummies.columns.tolist()

['Австралийская',
 'Австрийская',
 'Азиатская',
 'Албанская',
 'Алжирская',
 'Американская',
 'Арабская',
 'Аргентинская',
 'Армянская',
 'Афганская',
 'Африканская',
 'Бангладешская',
 'Бар',
 'Барбекю',
 'Бары и клубы',
 'Бары с рестораном',
 'Баскская',
 'Бельгийская',
 'Ближневосточная',
 'Бразильская',
 'Британская',
 'Венесуэльская',
 'Винный бар',
 'Восточноевропейская',
 'Вьетнамская',
 'Гавайская',
 'Гастроном',
 'Гастропаб',
 'Греческая',
 'Гриль',
 'Грузинская',
 'Датская',
 'Десерты',
 'Европейская',
 'Закусочная',
 'Здоровая',
 'Израильская',
 'Индийская',
 'Ирландская',
 'Испанская',
 'Итальянская',
 'Каджунская и креольская',
 'Кайсэки',
 'Камбоджийская',
 'Канадская',
 'Кантонская',
 'Карибская',
 'Кафе',
 'Китайская',
 'Колумбийская',
 'Корейская',
 'Кубинская',
 'Латиноамериканская',
 'Ливанская',
 'Малазийская',
 'Марокканская',
 'Международная',
 'Мексиканская',
 'Меню',
 'Морепродукты',
 'Немецкая',
 'Непальская',
 'Нонья',
 'Открыто сейчас',
 'Паб',
 'Паб с пивоварней',
 'Пакистанская',
 'Персидская',
 'Перуанская',
 'Пицца',
 'Польская',
 'Португальская',
 'Пуэрториканская',
 'Римская',
 'Румынская',
 'Русская',
 'Северно-итальянская',
 'Сегодня выходной',
 'Сейчас закрыто',
 'Сингапурская',
 'Сицилийская',
 'Современная',
 'Средиземноморская',
 'Стейк-хаус',
 'Супы',
 'Суши',
 'Сычуаньская',
 'Тайваньская',
 'Тайская',
 'Тибетская',
 'Тосканская',
 'Турецкая',
 'Узбекская',
 'Украинская',
 'Уличная еда',
 'Фастфуд',
 'Филиппинская',
 'Французская',
 'Фьюжн',
 'Хорватская',
 'Центральноазиатская',
 'Центральноамериканская',
 'Чешская',
 'Чилийская',
 'Шанхайская',
 'Шведская',
 'Швейцарская',
 'Шриланкийская',
 'Эфиопская',
 'Юговосточная',
 'Южно-итальянская',
 'Южноамериканская',
 'Юнаньская',
 'Ямайская',
 'Японская',
 'Японская кухня-фьюжн']

In [27]:
df = pd.concat([df, cuisine_dummies], axis=1)